FROM eclipse-temurin:17-jdk as build
WORKDIR /work
COPY . /work/

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /work/target/quarkus-app/ /app/

CMD ["java", "-jar", "/app/quarkus-run.jar"]
EXPOSE 8080