## Baseimage for the Build-Stage
FROM openjdk:17

## Conterxt wurder im der Composefile auf rootfolder gesetzt.
## Kopiere alles in den Container
COPY . /work/

## Set WORKDIR to quarkus-app for the ENTRYPOINT
WORKDIR /work/target/quarkus-app/

## SET what happens in ENTRYPOINT
ENTRYPOINT ["java" ,"-jar", "quarkus-run.jar"]