GET http://localhost:8080/journal/getAllJournals


###
POST http://localhost:8080/journal/createJournalEntry
Content-Type: application/json



{
    "title": "neuer mew",
    "subtitle": "test3",
    "date": "2004-08-08",
    "content": "TEST"
}
###
DELETE http://localhost:8080/journal/delete/2



